// Code generated by glow (https://github.com/go-gl/glow). DO NOT EDIT.

package wgl

import (
	"errors"
	"math"
	"syscall"
	"unsafe"
)

var (
	gpChoosePixelFormat                 uintptr
	gpDescribePixelFormat               uintptr
	gpGetEnhMetaFilePixelFormat         uintptr
	gpGetPixelFormat                    uintptr
	gpSetPixelFormat                    uintptr
	gpSwapBuffers                       uintptr
	gpAllocateMemoryNV                  uintptr
	gpAssociateImageBufferEventsI3D     uintptr
	gpBeginFrameTrackingI3D             uintptr
	gpBindDisplayColorTableEXT          uintptr
	gpBindSwapBarrierNV                 uintptr
	gpBindTexImageARB                   uintptr
	gpBindVideoCaptureDeviceNV          uintptr
	gpBindVideoDeviceNV                 uintptr
	gpBindVideoImageNV                  uintptr
	gpBlitContextFramebufferAMD         uintptr
	gpChoosePixelFormatARB              uintptr
	gpChoosePixelFormatEXT              uintptr
	gpCopyContext                       uintptr
	gpCopyImageSubDataNV                uintptr
	gpCreateAffinityDCNV                uintptr
	gpCreateAssociatedContextAMD        uintptr
	gpCreateAssociatedContextAttribsAMD uintptr
	gpCreateBufferRegionARB             uintptr
	gpCreateContext                     uintptr
	gpCreateContextAttribsARB           uintptr
	gpCreateDisplayColorTableEXT        uintptr
	gpCreateImageBufferI3D              uintptr
	gpCreateLayerContext                uintptr
	gpCreatePbufferARB                  uintptr
	gpCreatePbufferEXT                  uintptr
	gpDXCloseDeviceNV                   uintptr
	gpDXLockObjectsNV                   uintptr
	gpDXObjectAccessNV                  uintptr
	gpDXOpenDeviceNV                    uintptr
	gpDXRegisterObjectNV                uintptr
	gpDXSetResourceShareHandleNV        uintptr
	gpDXUnlockObjectsNV                 uintptr
	gpDXUnregisterObjectNV              uintptr
	gpDelayBeforeSwapNV                 uintptr
	gpDeleteAssociatedContextAMD        uintptr
	gpDeleteBufferRegionARB             uintptr
	gpDeleteContext                     uintptr
	gpDeleteDCNV                        uintptr
	gpDescribeLayerPlane                uintptr
	gpDestroyDisplayColorTableEXT       uintptr
	gpDestroyImageBufferI3D             uintptr
	gpDestroyPbufferARB                 uintptr
	gpDestroyPbufferEXT                 uintptr
	gpDisableFrameLockI3D               uintptr
	gpDisableGenlockI3D                 uintptr
	gpEnableFrameLockI3D                uintptr
	gpEnableGenlockI3D                  uintptr
	gpEndFrameTrackingI3D               uintptr
	gpEnumGpuDevicesNV                  uintptr
	gpEnumGpusFromAffinityDCNV          uintptr
	gpEnumGpusNV                        uintptr
	gpEnumerateVideoCaptureDevicesNV    uintptr
	gpEnumerateVideoDevicesNV           uintptr
	gpFreeMemoryNV                      uintptr
	gpGenlockSampleRateI3D              uintptr
	gpGenlockSourceDelayI3D             uintptr
	gpGenlockSourceEdgeI3D              uintptr
	gpGenlockSourceI3D                  uintptr
	gpGetContextGPUIDAMD                uintptr
	gpGetCurrentAssociatedContextAMD    uintptr
	gpGetCurrentContext                 uintptr
	gpGetCurrentDC                      uintptr
	gpGetCurrentReadDCARB               uintptr
	gpGetCurrentReadDCEXT               uintptr
	gpGetDigitalVideoParametersI3D      uintptr
	gpGetExtensionsStringARB            uintptr
	gpGetExtensionsStringEXT            uintptr
	gpGetFrameUsageI3D                  uintptr
	gpGetGPUIDsAMD                      uintptr
	gpGetGPUInfoAMD                     uintptr
	gpGetGammaTableI3D                  uintptr
	gpGetGammaTableParametersI3D        uintptr
	gpGetGenlockSampleRateI3D           uintptr
	gpGetGenlockSourceDelayI3D          uintptr
	gpGetGenlockSourceEdgeI3D           uintptr
	gpGetGenlockSourceI3D               uintptr
	gpGetLayerPaletteEntries            uintptr
	gpGetMscRateOML                     uintptr
	gpGetPbufferDCARB                   uintptr
	gpGetPbufferDCEXT                   uintptr
	gpGetPixelFormatAttribfvARB         uintptr
	gpGetPixelFormatAttribfvEXT         uintptr
	gpGetPixelFormatAttribivARB         uintptr
	gpGetPixelFormatAttribivEXT         uintptr
	gpGetProcAddress                    uintptr
	gpGetSwapIntervalEXT                uintptr
	gpGetSyncValuesOML                  uintptr
	gpGetVideoDeviceNV                  uintptr
	gpGetVideoInfoNV                    uintptr
	gpIsEnabledFrameLockI3D             uintptr
	gpIsEnabledGenlockI3D               uintptr
	gpJoinSwapGroupNV                   uintptr
	gpLoadDisplayColorTableEXT          uintptr
	gpLockVideoCaptureDeviceNV          uintptr
	gpMakeAssociatedContextCurrentAMD   uintptr
	gpMakeContextCurrentARB             uintptr
	gpMakeContextCurrentEXT             uintptr
	gpMakeCurrent                       uintptr
	gpQueryCurrentContextNV             uintptr
	gpQueryFrameCountNV                 uintptr
	gpQueryFrameLockMasterI3D           uintptr
	gpQueryFrameTrackingI3D             uintptr
	gpQueryGenlockMaxSourceDelayI3D     uintptr
	gpQueryMaxSwapGroupsNV              uintptr
	gpQueryPbufferARB                   uintptr
	gpQueryPbufferEXT                   uintptr
	gpQuerySwapGroupNV                  uintptr
	gpQueryVideoCaptureDeviceNV         uintptr
	gpRealizeLayerPalette               uintptr
	gpReleaseImageBufferEventsI3D       uintptr
	gpReleasePbufferDCARB               uintptr
	gpReleasePbufferDCEXT               uintptr
	gpReleaseTexImageARB                uintptr
	gpReleaseVideoCaptureDeviceNV       uintptr
	gpReleaseVideoDeviceNV              uintptr
	gpReleaseVideoImageNV               uintptr
	gpResetFrameCountNV                 uintptr
	gpRestoreBufferRegionARB            uintptr
	gpSaveBufferRegionARB               uintptr
	gpSendPbufferToVideoNV              uintptr
	gpSetDigitalVideoParametersI3D      uintptr
	gpSetGammaTableI3D                  uintptr
	gpSetGammaTableParametersI3D        uintptr
	gpSetLayerPaletteEntries            uintptr
	gpSetPbufferAttribARB               uintptr
	gpSetStereoEmitterState3DL          uintptr
	gpShareLists                        uintptr
	gpSwapBuffersMscOML                 uintptr
	gpSwapIntervalEXT                   uintptr
	gpSwapLayerBuffers                  uintptr
	gpSwapLayerBuffersMscOML            uintptr
	gpUseFontBitmaps                    uintptr
	gpUseFontOutlines                   uintptr
	gpWaitForMscOML                     uintptr
	gpWaitForSbcOML                     uintptr
)

func boolToUintptr(b bool) uintptr {
	if b {
		return 1
	}
	return 0
}

// Parameter hDc has type C.HDC.
// Parameter pPfd has type *C.PIXELFORMATDESCRIPTOR.
// Return value has type C.int.
func ChoosePixelFormat(hDc unsafe.Pointer, pPfd unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpChoosePixelFormat, 2, uintptr(hDc), uintptr(pPfd), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter ipfd has type C.int.
// Parameter cjpfd has type C.UINT.
// Parameter ppfd has type *C.PIXELFORMATDESCRIPTOR.
// Return value has type C.int.
func DescribePixelFormat(hdc unsafe.Pointer, ipfd unsafe.Pointer, cjpfd unsafe.Pointer, ppfd unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpDescribePixelFormat, 4, uintptr(hdc), uintptr(ipfd), uintptr(cjpfd), uintptr(ppfd), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hemf has type C.HENHMETAFILE.
// Parameter ppfd has type *C.PIXELFORMATDESCRIPTOR.
// Return value has type C.UINT.
func GetEnhMetaFilePixelFormat(hemf unsafe.Pointer, ppfd unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetEnhMetaFilePixelFormat, 2, uintptr(hemf), uintptr(ppfd), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Return value has type C.int.
func GetPixelFormat(hdc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetPixelFormat, 1, uintptr(hdc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter ipfd has type C.int.
// Parameter ppfd has type *C.PIXELFORMATDESCRIPTOR.
// Return value has type C.BOOL.
func SetPixelFormat(hdc unsafe.Pointer, ipfd unsafe.Pointer, ppfd unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpSetPixelFormat, 3, uintptr(hdc), uintptr(ipfd), uintptr(ppfd))
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Return value has type C.BOOL.
func SwapBuffers(hdc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpSwapBuffers, 1, uintptr(hdc), 0, 0)
	return (unsafe.Pointer)(ret)
}
func AllocateMemoryNV(size int32, readfreq float32, writefreq float32, priority float32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpAllocateMemoryNV, 4, uintptr(size), uintptr(math.Float32bits(readfreq)), uintptr(math.Float32bits(writefreq)), uintptr(math.Float32bits(priority)), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter pEvent has type *C.HANDLE.
// Parameter pAddress has type *C.LPVOID.
// Parameter pSize has type *C.DWORD.
// Parameter count has type C.UINT.
// Return value has type C.BOOL.
func AssociateImageBufferEventsI3D(hDC unsafe.Pointer, pEvent unsafe.Pointer, pAddress unsafe.Pointer, pSize unsafe.Pointer, count unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpAssociateImageBufferEventsI3D, 5, uintptr(hDC), uintptr(pEvent), uintptr(pAddress), uintptr(pSize), uintptr(count), 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.BOOL.
func BeginFrameTrackingI3D() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpBeginFrameTrackingI3D, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}
func BindDisplayColorTableEXT(id uint16) bool {
	ret, _, _ := syscall.Syscall(gpBindDisplayColorTableEXT, 1, uintptr(id), 0, 0)
	return ret != 0
}

// Return value has type C.BOOL.
func BindSwapBarrierNV(group uint32, barrier uint32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpBindSwapBarrierNV, 2, uintptr(group), uintptr(barrier), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Parameter iBuffer has type C.int.
// Return value has type C.BOOL.
func BindTexImageARB(hPbuffer unsafe.Pointer, iBuffer unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpBindTexImageARB, 2, uintptr(hPbuffer), uintptr(iBuffer), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter uVideoSlot has type C.UINT.
// Parameter hDevice has type C.HVIDEOINPUTDEVICENV.
// Return value has type C.BOOL.
func BindVideoCaptureDeviceNV(uVideoSlot unsafe.Pointer, hDevice unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpBindVideoCaptureDeviceNV, 2, uintptr(uVideoSlot), uintptr(hDevice), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uVideoSlot has type C.unsignedint.
// Parameter hVideoDevice has type C.HVIDEOOUTPUTDEVICENV.
// Parameter piAttribList has type *C.int.
// Return value has type C.BOOL.
func BindVideoDeviceNV(hDC unsafe.Pointer, uVideoSlot unsafe.Pointer, hVideoDevice unsafe.Pointer, piAttribList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpBindVideoDeviceNV, 4, uintptr(hDC), uintptr(uVideoSlot), uintptr(hVideoDevice), uintptr(piAttribList), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hVideoDevice has type C.HPVIDEODEV.
// Parameter hPbuffer has type C.HPBUFFERARB.
// Parameter iVideoBuffer has type C.int.
// Return value has type C.BOOL.
func BindVideoImageNV(hVideoDevice unsafe.Pointer, hPbuffer unsafe.Pointer, iVideoBuffer unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpBindVideoImageNV, 3, uintptr(hVideoDevice), uintptr(hPbuffer), uintptr(iVideoBuffer))
	return (unsafe.Pointer)(ret)
}

// Parameter dstCtx has type C.HGLRC.
// Return value has type C.VOID.
func BlitContextFramebufferAMD(dstCtx unsafe.Pointer, srcX0 int32, srcY0 int32, srcX1 int32, srcY1 int32, dstX0 int32, dstY0 int32, dstX1 int32, dstY1 int32, mask uint32, filter uint32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall12(gpBlitContextFramebufferAMD, 11, uintptr(dstCtx), uintptr(srcX0), uintptr(srcY0), uintptr(srcX1), uintptr(srcY1), uintptr(dstX0), uintptr(dstY0), uintptr(dstX1), uintptr(dstY1), uintptr(mask), uintptr(filter), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter piAttribIList has type *C.int.
// Parameter pfAttribFList has type *C.FLOAT.
// Parameter nMaxFormats has type C.UINT.
// Parameter piFormats has type *C.int.
// Parameter nNumFormats has type *C.UINT.
// Return value has type C.BOOL.
func ChoosePixelFormatARB(hdc unsafe.Pointer, piAttribIList unsafe.Pointer, pfAttribFList unsafe.Pointer, nMaxFormats unsafe.Pointer, piFormats unsafe.Pointer, nNumFormats unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpChoosePixelFormatARB, 6, uintptr(hdc), uintptr(piAttribIList), uintptr(pfAttribFList), uintptr(nMaxFormats), uintptr(piFormats), uintptr(nNumFormats))
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter piAttribIList has type *C.int.
// Parameter pfAttribFList has type *C.FLOAT.
// Parameter nMaxFormats has type C.UINT.
// Parameter piFormats has type *C.int.
// Parameter nNumFormats has type *C.UINT.
// Return value has type C.BOOL.
func ChoosePixelFormatEXT(hdc unsafe.Pointer, piAttribIList unsafe.Pointer, pfAttribFList unsafe.Pointer, nMaxFormats unsafe.Pointer, piFormats unsafe.Pointer, nNumFormats unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpChoosePixelFormatEXT, 6, uintptr(hdc), uintptr(piAttribIList), uintptr(pfAttribFList), uintptr(nMaxFormats), uintptr(piFormats), uintptr(nNumFormats))
	return (unsafe.Pointer)(ret)
}

// Parameter hglrcSrc has type C.HGLRC.
// Parameter hglrcDst has type C.HGLRC.
// Parameter mask has type C.UINT.
// Return value has type C.BOOL.
func CopyContext(hglrcSrc unsafe.Pointer, hglrcDst unsafe.Pointer, mask unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCopyContext, 3, uintptr(hglrcSrc), uintptr(hglrcDst), uintptr(mask))
	return (unsafe.Pointer)(ret)
}

// Parameter hSrcRC has type C.HGLRC.
// Parameter hDstRC has type C.HGLRC.
// Return value has type C.BOOL.
func CopyImageSubDataNV(hSrcRC unsafe.Pointer, srcName uint32, srcTarget uint32, srcLevel int32, srcX int32, srcY int32, srcZ int32, hDstRC unsafe.Pointer, dstName uint32, dstTarget uint32, dstLevel int32, dstX int32, dstY int32, dstZ int32, width int32, height int32, depth int32) unsafe.Pointer {
	panic("\"CopyImageSubDataNV\" is not implemented")
}

// Parameter phGpuList has type *C.HGPUNV.
// Return value has type C.HDC.
func CreateAffinityDCNV(phGpuList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCreateAffinityDCNV, 1, uintptr(phGpuList), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter id has type C.UINT.
// Return value has type C.HGLRC.
func CreateAssociatedContextAMD(id unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCreateAssociatedContextAMD, 1, uintptr(id), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter id has type C.UINT.
// Parameter hShareContext has type C.HGLRC.
// Parameter attribList has type *C.int.
// Return value has type C.HGLRC.
func CreateAssociatedContextAttribsAMD(id unsafe.Pointer, hShareContext unsafe.Pointer, attribList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCreateAssociatedContextAttribsAMD, 3, uintptr(id), uintptr(hShareContext), uintptr(attribList))
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iLayerPlane has type C.int.
// Parameter uType has type C.UINT.
// Return value has type C.HANDLE.
func CreateBufferRegionARB(hDC unsafe.Pointer, iLayerPlane unsafe.Pointer, uType unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCreateBufferRegionARB, 3, uintptr(hDC), uintptr(iLayerPlane), uintptr(uType))
	return (unsafe.Pointer)(ret)
}

// Parameter hDc has type C.HDC.
// Return value has type C.HGLRC.
func CreateContext(hDc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCreateContext, 1, uintptr(hDc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter hShareContext has type C.HGLRC.
// Parameter attribList has type *C.int.
// Return value has type C.HGLRC.
func CreateContextAttribsARB(hDC unsafe.Pointer, hShareContext unsafe.Pointer, attribList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCreateContextAttribsARB, 3, uintptr(hDC), uintptr(hShareContext), uintptr(attribList))
	return (unsafe.Pointer)(ret)
}
func CreateDisplayColorTableEXT(id uint16) bool {
	ret, _, _ := syscall.Syscall(gpCreateDisplayColorTableEXT, 1, uintptr(id), 0, 0)
	return ret != 0
}

// Parameter hDC has type C.HDC.
// Parameter dwSize has type C.DWORD.
// Parameter uFlags has type C.UINT.
// Return value has type C.LPVOID.
func CreateImageBufferI3D(hDC unsafe.Pointer, dwSize unsafe.Pointer, uFlags unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCreateImageBufferI3D, 3, uintptr(hDC), uintptr(dwSize), uintptr(uFlags))
	return (unsafe.Pointer)(ret)
}

// Parameter hDc has type C.HDC.
// Parameter level has type C.int.
// Return value has type C.HGLRC.
func CreateLayerContext(hDc unsafe.Pointer, level unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpCreateLayerContext, 2, uintptr(hDc), uintptr(level), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iPixelFormat has type C.int.
// Parameter iWidth has type C.int.
// Parameter iHeight has type C.int.
// Parameter piAttribList has type *C.int.
// Return value has type C.HPBUFFERARB.
func CreatePbufferARB(hDC unsafe.Pointer, iPixelFormat unsafe.Pointer, iWidth unsafe.Pointer, iHeight unsafe.Pointer, piAttribList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpCreatePbufferARB, 5, uintptr(hDC), uintptr(iPixelFormat), uintptr(iWidth), uintptr(iHeight), uintptr(piAttribList), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iPixelFormat has type C.int.
// Parameter iWidth has type C.int.
// Parameter iHeight has type C.int.
// Parameter piAttribList has type *C.int.
// Return value has type C.HPBUFFEREXT.
func CreatePbufferEXT(hDC unsafe.Pointer, iPixelFormat unsafe.Pointer, iWidth unsafe.Pointer, iHeight unsafe.Pointer, piAttribList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpCreatePbufferEXT, 5, uintptr(hDC), uintptr(iPixelFormat), uintptr(iWidth), uintptr(iHeight), uintptr(piAttribList), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDevice has type C.HANDLE.
// Return value has type C.BOOL.
func DXCloseDeviceNV(hDevice unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDXCloseDeviceNV, 1, uintptr(hDevice), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDevice has type C.HANDLE.
// Parameter hObjects has type *C.HANDLE.
// Return value has type C.BOOL.
func DXLockObjectsNV(hDevice unsafe.Pointer, count int32, hObjects unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDXLockObjectsNV, 3, uintptr(hDevice), uintptr(count), uintptr(hObjects))
	return (unsafe.Pointer)(ret)
}

// Parameter hObject has type C.HANDLE.
// Return value has type C.BOOL.
func DXObjectAccessNV(hObject unsafe.Pointer, access uint32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDXObjectAccessNV, 2, uintptr(hObject), uintptr(access), 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.HANDLE.
func DXOpenDeviceNV(dxDevice unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDXOpenDeviceNV, 1, uintptr(dxDevice), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDevice has type C.HANDLE.
// Return value has type C.HANDLE.
func DXRegisterObjectNV(hDevice unsafe.Pointer, dxObject unsafe.Pointer, name uint32, xtype uint32, access uint32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpDXRegisterObjectNV, 5, uintptr(hDevice), uintptr(dxObject), uintptr(name), uintptr(xtype), uintptr(access), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter shareHandle has type C.HANDLE.
// Return value has type C.BOOL.
func DXSetResourceShareHandleNV(dxObject unsafe.Pointer, shareHandle unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDXSetResourceShareHandleNV, 2, uintptr(dxObject), uintptr(shareHandle), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDevice has type C.HANDLE.
// Parameter hObjects has type *C.HANDLE.
// Return value has type C.BOOL.
func DXUnlockObjectsNV(hDevice unsafe.Pointer, count int32, hObjects unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDXUnlockObjectsNV, 3, uintptr(hDevice), uintptr(count), uintptr(hObjects))
	return (unsafe.Pointer)(ret)
}

// Parameter hDevice has type C.HANDLE.
// Parameter hObject has type C.HANDLE.
// Return value has type C.BOOL.
func DXUnregisterObjectNV(hDevice unsafe.Pointer, hObject unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDXUnregisterObjectNV, 2, uintptr(hDevice), uintptr(hObject), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Return value has type C.BOOL.
func DelayBeforeSwapNV(hDC unsafe.Pointer, seconds float32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDelayBeforeSwapNV, 2, uintptr(hDC), uintptr(math.Float32bits(seconds)), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hglrc has type C.HGLRC.
// Return value has type C.BOOL.
func DeleteAssociatedContextAMD(hglrc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDeleteAssociatedContextAMD, 1, uintptr(hglrc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hRegion has type C.HANDLE.
// Return value has type C.VOID.
func DeleteBufferRegionARB(hRegion unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDeleteBufferRegionARB, 1, uintptr(hRegion), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter oldContext has type C.HGLRC.
// Return value has type C.BOOL.
func DeleteContext(oldContext unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDeleteContext, 1, uintptr(oldContext), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Return value has type C.BOOL.
func DeleteDCNV(hdc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDeleteDCNV, 1, uintptr(hdc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDc has type C.HDC.
// Parameter pixelFormat has type C.int.
// Parameter layerPlane has type C.int.
// Parameter nBytes has type C.UINT.
// Parameter plpd has type *C.LAYERPLANEDESCRIPTOR.
// Return value has type C.BOOL.
func DescribeLayerPlane(hDc unsafe.Pointer, pixelFormat unsafe.Pointer, layerPlane unsafe.Pointer, nBytes unsafe.Pointer, plpd unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpDescribeLayerPlane, 5, uintptr(hDc), uintptr(pixelFormat), uintptr(layerPlane), uintptr(nBytes), uintptr(plpd), 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.VOID.
func DestroyDisplayColorTableEXT(id uint16) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDestroyDisplayColorTableEXT, 1, uintptr(id), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter pAddress has type C.LPVOID.
// Return value has type C.BOOL.
func DestroyImageBufferI3D(hDC unsafe.Pointer, pAddress unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDestroyImageBufferI3D, 2, uintptr(hDC), uintptr(pAddress), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Return value has type C.BOOL.
func DestroyPbufferARB(hPbuffer unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDestroyPbufferARB, 1, uintptr(hPbuffer), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFEREXT.
// Return value has type C.BOOL.
func DestroyPbufferEXT(hPbuffer unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDestroyPbufferEXT, 1, uintptr(hPbuffer), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.BOOL.
func DisableFrameLockI3D() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDisableFrameLockI3D, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Return value has type C.BOOL.
func DisableGenlockI3D(hDC unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpDisableGenlockI3D, 1, uintptr(hDC), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.BOOL.
func EnableFrameLockI3D() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpEnableFrameLockI3D, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Return value has type C.BOOL.
func EnableGenlockI3D(hDC unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpEnableGenlockI3D, 1, uintptr(hDC), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.BOOL.
func EndFrameTrackingI3D() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpEndFrameTrackingI3D, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hGpu has type C.HGPUNV.
// Parameter iDeviceIndex has type C.UINT.
// Parameter lpGpuDevice has type C.PGPU_DEVICE.
// Return value has type C.BOOL.
func EnumGpuDevicesNV(hGpu unsafe.Pointer, iDeviceIndex unsafe.Pointer, lpGpuDevice unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpEnumGpuDevicesNV, 3, uintptr(hGpu), uintptr(iDeviceIndex), uintptr(lpGpuDevice))
	return (unsafe.Pointer)(ret)
}

// Parameter hAffinityDC has type C.HDC.
// Parameter iGpuIndex has type C.UINT.
// Parameter hGpu has type *C.HGPUNV.
// Return value has type C.BOOL.
func EnumGpusFromAffinityDCNV(hAffinityDC unsafe.Pointer, iGpuIndex unsafe.Pointer, hGpu unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpEnumGpusFromAffinityDCNV, 3, uintptr(hAffinityDC), uintptr(iGpuIndex), uintptr(hGpu))
	return (unsafe.Pointer)(ret)
}

// Parameter iGpuIndex has type C.UINT.
// Parameter phGpu has type *C.HGPUNV.
// Return value has type C.BOOL.
func EnumGpusNV(iGpuIndex unsafe.Pointer, phGpu unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpEnumGpusNV, 2, uintptr(iGpuIndex), uintptr(phGpu), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDc has type C.HDC.
// Parameter phDeviceList has type *C.HVIDEOINPUTDEVICENV.
// Return value has type C.UINT.
func EnumerateVideoCaptureDevicesNV(hDc unsafe.Pointer, phDeviceList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpEnumerateVideoCaptureDevicesNV, 2, uintptr(hDc), uintptr(phDeviceList), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter phDeviceList has type *C.HVIDEOOUTPUTDEVICENV.
// Return value has type C.int.
func EnumerateVideoDevicesNV(hDC unsafe.Pointer, phDeviceList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpEnumerateVideoDevicesNV, 2, uintptr(hDC), uintptr(phDeviceList), 0)
	return (unsafe.Pointer)(ret)
}
func FreeMemoryNV(pointer unsafe.Pointer) {
	syscall.Syscall(gpFreeMemoryNV, 1, uintptr(pointer), 0, 0)
}

// Parameter hDC has type C.HDC.
// Parameter uRate has type C.UINT.
// Return value has type C.BOOL.
func GenlockSampleRateI3D(hDC unsafe.Pointer, uRate unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGenlockSampleRateI3D, 2, uintptr(hDC), uintptr(uRate), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uDelay has type C.UINT.
// Return value has type C.BOOL.
func GenlockSourceDelayI3D(hDC unsafe.Pointer, uDelay unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGenlockSourceDelayI3D, 2, uintptr(hDC), uintptr(uDelay), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uEdge has type C.UINT.
// Return value has type C.BOOL.
func GenlockSourceEdgeI3D(hDC unsafe.Pointer, uEdge unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGenlockSourceEdgeI3D, 2, uintptr(hDC), uintptr(uEdge), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uSource has type C.UINT.
// Return value has type C.BOOL.
func GenlockSourceI3D(hDC unsafe.Pointer, uSource unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGenlockSourceI3D, 2, uintptr(hDC), uintptr(uSource), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hglrc has type C.HGLRC.
// Return value has type C.UINT.
func GetContextGPUIDAMD(hglrc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetContextGPUIDAMD, 1, uintptr(hglrc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.HGLRC.
func GetCurrentAssociatedContextAMD() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetCurrentAssociatedContextAMD, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.HGLRC.
func GetCurrentContext() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetCurrentContext, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.HDC.
func GetCurrentDC() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetCurrentDC, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.HDC.
func GetCurrentReadDCARB() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetCurrentReadDCARB, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.HDC.
func GetCurrentReadDCEXT() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetCurrentReadDCEXT, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iAttribute has type C.int.
// Parameter piValue has type *C.int.
// Return value has type C.BOOL.
func GetDigitalVideoParametersI3D(hDC unsafe.Pointer, iAttribute unsafe.Pointer, piValue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetDigitalVideoParametersI3D, 3, uintptr(hDC), uintptr(iAttribute), uintptr(piValue))
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Return value has type *C.char.
func GetExtensionsStringARB(hdc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetExtensionsStringARB, 1, uintptr(hdc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type *C.char.
func GetExtensionsStringEXT() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetExtensionsStringEXT, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter pUsage has type *C.float.
// Return value has type C.BOOL.
func GetFrameUsageI3D(pUsage unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetFrameUsageI3D, 1, uintptr(pUsage), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter maxCount has type C.UINT.
// Parameter ids has type *C.UINT.
// Return value has type C.UINT.
func GetGPUIDsAMD(maxCount unsafe.Pointer, ids unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetGPUIDsAMD, 2, uintptr(maxCount), uintptr(ids), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter id has type C.UINT.
// Parameter property has type C.int.
// Parameter size has type C.UINT.
// Return value has type C.INT.
func GetGPUInfoAMD(id unsafe.Pointer, property unsafe.Pointer, dataType uint32, size unsafe.Pointer, data unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpGetGPUInfoAMD, 5, uintptr(id), uintptr(property), uintptr(dataType), uintptr(size), uintptr(data), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iEntries has type C.int.
// Parameter puRed has type *C.USHORT.
// Parameter puGreen has type *C.USHORT.
// Parameter puBlue has type *C.USHORT.
// Return value has type C.BOOL.
func GetGammaTableI3D(hDC unsafe.Pointer, iEntries unsafe.Pointer, puRed unsafe.Pointer, puGreen unsafe.Pointer, puBlue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpGetGammaTableI3D, 5, uintptr(hDC), uintptr(iEntries), uintptr(puRed), uintptr(puGreen), uintptr(puBlue), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iAttribute has type C.int.
// Parameter piValue has type *C.int.
// Return value has type C.BOOL.
func GetGammaTableParametersI3D(hDC unsafe.Pointer, iAttribute unsafe.Pointer, piValue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetGammaTableParametersI3D, 3, uintptr(hDC), uintptr(iAttribute), uintptr(piValue))
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uRate has type *C.UINT.
// Return value has type C.BOOL.
func GetGenlockSampleRateI3D(hDC unsafe.Pointer, uRate unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetGenlockSampleRateI3D, 2, uintptr(hDC), uintptr(uRate), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uDelay has type *C.UINT.
// Return value has type C.BOOL.
func GetGenlockSourceDelayI3D(hDC unsafe.Pointer, uDelay unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetGenlockSourceDelayI3D, 2, uintptr(hDC), uintptr(uDelay), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uEdge has type *C.UINT.
// Return value has type C.BOOL.
func GetGenlockSourceEdgeI3D(hDC unsafe.Pointer, uEdge unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetGenlockSourceEdgeI3D, 2, uintptr(hDC), uintptr(uEdge), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uSource has type *C.UINT.
// Return value has type C.BOOL.
func GetGenlockSourceI3D(hDC unsafe.Pointer, uSource unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetGenlockSourceI3D, 2, uintptr(hDC), uintptr(uSource), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter iLayerPlane has type C.int.
// Parameter iStart has type C.int.
// Parameter cEntries has type C.int.
// Parameter pcr has type *C.COLORREF.
// Return value has type C.int.
func GetLayerPaletteEntries(hdc unsafe.Pointer, iLayerPlane unsafe.Pointer, iStart unsafe.Pointer, cEntries unsafe.Pointer, pcr unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpGetLayerPaletteEntries, 5, uintptr(hdc), uintptr(iLayerPlane), uintptr(iStart), uintptr(cEntries), uintptr(pcr), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter numerator has type *C.INT32.
// Parameter denominator has type *C.INT32.
// Return value has type C.BOOL.
func GetMscRateOML(hdc unsafe.Pointer, numerator unsafe.Pointer, denominator unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetMscRateOML, 3, uintptr(hdc), uintptr(numerator), uintptr(denominator))
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Return value has type C.HDC.
func GetPbufferDCARB(hPbuffer unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetPbufferDCARB, 1, uintptr(hPbuffer), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFEREXT.
// Return value has type C.HDC.
func GetPbufferDCEXT(hPbuffer unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetPbufferDCEXT, 1, uintptr(hPbuffer), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter iPixelFormat has type C.int.
// Parameter iLayerPlane has type C.int.
// Parameter nAttributes has type C.UINT.
// Parameter piAttributes has type *C.int.
// Parameter pfValues has type *C.FLOAT.
// Return value has type C.BOOL.
func GetPixelFormatAttribfvARB(hdc unsafe.Pointer, iPixelFormat unsafe.Pointer, iLayerPlane unsafe.Pointer, nAttributes unsafe.Pointer, piAttributes unsafe.Pointer, pfValues unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpGetPixelFormatAttribfvARB, 6, uintptr(hdc), uintptr(iPixelFormat), uintptr(iLayerPlane), uintptr(nAttributes), uintptr(piAttributes), uintptr(pfValues))
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter iPixelFormat has type C.int.
// Parameter iLayerPlane has type C.int.
// Parameter nAttributes has type C.UINT.
// Parameter piAttributes has type *C.int.
// Parameter pfValues has type *C.FLOAT.
// Return value has type C.BOOL.
func GetPixelFormatAttribfvEXT(hdc unsafe.Pointer, iPixelFormat unsafe.Pointer, iLayerPlane unsafe.Pointer, nAttributes unsafe.Pointer, piAttributes unsafe.Pointer, pfValues unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpGetPixelFormatAttribfvEXT, 6, uintptr(hdc), uintptr(iPixelFormat), uintptr(iLayerPlane), uintptr(nAttributes), uintptr(piAttributes), uintptr(pfValues))
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter iPixelFormat has type C.int.
// Parameter iLayerPlane has type C.int.
// Parameter nAttributes has type C.UINT.
// Parameter piAttributes has type *C.int.
// Parameter piValues has type *C.int.
// Return value has type C.BOOL.
func GetPixelFormatAttribivARB(hdc unsafe.Pointer, iPixelFormat unsafe.Pointer, iLayerPlane unsafe.Pointer, nAttributes unsafe.Pointer, piAttributes unsafe.Pointer, piValues unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpGetPixelFormatAttribivARB, 6, uintptr(hdc), uintptr(iPixelFormat), uintptr(iLayerPlane), uintptr(nAttributes), uintptr(piAttributes), uintptr(piValues))
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter iPixelFormat has type C.int.
// Parameter iLayerPlane has type C.int.
// Parameter nAttributes has type C.UINT.
// Parameter piAttributes has type *C.int.
// Parameter piValues has type *C.int.
// Return value has type C.BOOL.
func GetPixelFormatAttribivEXT(hdc unsafe.Pointer, iPixelFormat unsafe.Pointer, iLayerPlane unsafe.Pointer, nAttributes unsafe.Pointer, piAttributes unsafe.Pointer, piValues unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpGetPixelFormatAttribivEXT, 6, uintptr(hdc), uintptr(iPixelFormat), uintptr(iLayerPlane), uintptr(nAttributes), uintptr(piAttributes), uintptr(piValues))
	return (unsafe.Pointer)(ret)
}

// Parameter lpszProc has type C.LPCSTR.
// Return value has type C.PROC.
func GetProcAddress(lpszProc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetProcAddress, 1, uintptr(lpszProc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Return value has type C.int.
func GetSwapIntervalEXT() unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetSwapIntervalEXT, 0, 0, 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter ust has type *C.INT64.
// Parameter msc has type *C.INT64.
// Parameter sbc has type *C.INT64.
// Return value has type C.BOOL.
func GetSyncValuesOML(hdc unsafe.Pointer, ust unsafe.Pointer, msc unsafe.Pointer, sbc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpGetSyncValuesOML, 4, uintptr(hdc), uintptr(ust), uintptr(msc), uintptr(sbc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter numDevices has type C.int.
// Parameter hVideoDevice has type *C.HPVIDEODEV.
// Return value has type C.BOOL.
func GetVideoDeviceNV(hDC unsafe.Pointer, numDevices unsafe.Pointer, hVideoDevice unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetVideoDeviceNV, 3, uintptr(hDC), uintptr(numDevices), uintptr(hVideoDevice))
	return (unsafe.Pointer)(ret)
}

// Parameter hpVideoDevice has type C.HPVIDEODEV.
// Parameter pulCounterOutputPbuffer has type *C.unsignedlong.
// Parameter pulCounterOutputVideo has type *C.unsignedlong.
// Return value has type C.BOOL.
func GetVideoInfoNV(hpVideoDevice unsafe.Pointer, pulCounterOutputPbuffer unsafe.Pointer, pulCounterOutputVideo unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpGetVideoInfoNV, 3, uintptr(hpVideoDevice), uintptr(pulCounterOutputPbuffer), uintptr(pulCounterOutputVideo))
	return (unsafe.Pointer)(ret)
}

// Parameter pFlag has type *C.BOOL.
// Return value has type C.BOOL.
func IsEnabledFrameLockI3D(pFlag unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpIsEnabledFrameLockI3D, 1, uintptr(pFlag), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter pFlag has type *C.BOOL.
// Return value has type C.BOOL.
func IsEnabledGenlockI3D(hDC unsafe.Pointer, pFlag unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpIsEnabledGenlockI3D, 2, uintptr(hDC), uintptr(pFlag), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Return value has type C.BOOL.
func JoinSwapGroupNV(hDC unsafe.Pointer, group uint32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpJoinSwapGroupNV, 2, uintptr(hDC), uintptr(group), 0)
	return (unsafe.Pointer)(ret)
}
func LoadDisplayColorTableEXT(table *uint16, length uint32) bool {
	ret, _, _ := syscall.Syscall(gpLoadDisplayColorTableEXT, 2, uintptr(unsafe.Pointer(table)), uintptr(length), 0)
	return ret != 0
}

// Parameter hDc has type C.HDC.
// Parameter hDevice has type C.HVIDEOINPUTDEVICENV.
// Return value has type C.BOOL.
func LockVideoCaptureDeviceNV(hDc unsafe.Pointer, hDevice unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpLockVideoCaptureDeviceNV, 2, uintptr(hDc), uintptr(hDevice), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hglrc has type C.HGLRC.
// Return value has type C.BOOL.
func MakeAssociatedContextCurrentAMD(hglrc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpMakeAssociatedContextCurrentAMD, 1, uintptr(hglrc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDrawDC has type C.HDC.
// Parameter hReadDC has type C.HDC.
// Parameter hglrc has type C.HGLRC.
// Return value has type C.BOOL.
func MakeContextCurrentARB(hDrawDC unsafe.Pointer, hReadDC unsafe.Pointer, hglrc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpMakeContextCurrentARB, 3, uintptr(hDrawDC), uintptr(hReadDC), uintptr(hglrc))
	return (unsafe.Pointer)(ret)
}

// Parameter hDrawDC has type C.HDC.
// Parameter hReadDC has type C.HDC.
// Parameter hglrc has type C.HGLRC.
// Return value has type C.BOOL.
func MakeContextCurrentEXT(hDrawDC unsafe.Pointer, hReadDC unsafe.Pointer, hglrc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpMakeContextCurrentEXT, 3, uintptr(hDrawDC), uintptr(hReadDC), uintptr(hglrc))
	return (unsafe.Pointer)(ret)
}

// Parameter hDc has type C.HDC.
// Parameter newContext has type C.HGLRC.
// Return value has type C.BOOL.
func MakeCurrent(hDc unsafe.Pointer, newContext unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpMakeCurrent, 2, uintptr(hDc), uintptr(newContext), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter iAttribute has type C.int.
// Parameter piValue has type *C.int.
// Return value has type C.BOOL.
func QueryCurrentContextNV(iAttribute unsafe.Pointer, piValue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQueryCurrentContextNV, 2, uintptr(iAttribute), uintptr(piValue), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Return value has type C.BOOL.
func QueryFrameCountNV(hDC unsafe.Pointer, count *uint32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQueryFrameCountNV, 2, uintptr(hDC), uintptr(unsafe.Pointer(count)), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter pFlag has type *C.BOOL.
// Return value has type C.BOOL.
func QueryFrameLockMasterI3D(pFlag unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQueryFrameLockMasterI3D, 1, uintptr(pFlag), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter pFrameCount has type *C.DWORD.
// Parameter pMissedFrames has type *C.DWORD.
// Parameter pLastMissedUsage has type *C.float.
// Return value has type C.BOOL.
func QueryFrameTrackingI3D(pFrameCount unsafe.Pointer, pMissedFrames unsafe.Pointer, pLastMissedUsage unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQueryFrameTrackingI3D, 3, uintptr(pFrameCount), uintptr(pMissedFrames), uintptr(pLastMissedUsage))
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uMaxLineDelay has type *C.UINT.
// Parameter uMaxPixelDelay has type *C.UINT.
// Return value has type C.BOOL.
func QueryGenlockMaxSourceDelayI3D(hDC unsafe.Pointer, uMaxLineDelay unsafe.Pointer, uMaxPixelDelay unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQueryGenlockMaxSourceDelayI3D, 3, uintptr(hDC), uintptr(uMaxLineDelay), uintptr(uMaxPixelDelay))
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Return value has type C.BOOL.
func QueryMaxSwapGroupsNV(hDC unsafe.Pointer, maxGroups *uint32, maxBarriers *uint32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQueryMaxSwapGroupsNV, 3, uintptr(hDC), uintptr(unsafe.Pointer(maxGroups)), uintptr(unsafe.Pointer(maxBarriers)))
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Parameter iAttribute has type C.int.
// Parameter piValue has type *C.int.
// Return value has type C.BOOL.
func QueryPbufferARB(hPbuffer unsafe.Pointer, iAttribute unsafe.Pointer, piValue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQueryPbufferARB, 3, uintptr(hPbuffer), uintptr(iAttribute), uintptr(piValue))
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFEREXT.
// Parameter iAttribute has type C.int.
// Parameter piValue has type *C.int.
// Return value has type C.BOOL.
func QueryPbufferEXT(hPbuffer unsafe.Pointer, iAttribute unsafe.Pointer, piValue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQueryPbufferEXT, 3, uintptr(hPbuffer), uintptr(iAttribute), uintptr(piValue))
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Return value has type C.BOOL.
func QuerySwapGroupNV(hDC unsafe.Pointer, group *uint32, barrier *uint32) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpQuerySwapGroupNV, 3, uintptr(hDC), uintptr(unsafe.Pointer(group)), uintptr(unsafe.Pointer(barrier)))
	return (unsafe.Pointer)(ret)
}

// Parameter hDc has type C.HDC.
// Parameter hDevice has type C.HVIDEOINPUTDEVICENV.
// Parameter iAttribute has type C.int.
// Parameter piValue has type *C.int.
// Return value has type C.BOOL.
func QueryVideoCaptureDeviceNV(hDc unsafe.Pointer, hDevice unsafe.Pointer, iAttribute unsafe.Pointer, piValue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpQueryVideoCaptureDeviceNV, 4, uintptr(hDc), uintptr(hDevice), uintptr(iAttribute), uintptr(piValue), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter iLayerPlane has type C.int.
// Parameter bRealize has type C.BOOL.
// Return value has type C.BOOL.
func RealizeLayerPalette(hdc unsafe.Pointer, iLayerPlane unsafe.Pointer, bRealize unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpRealizeLayerPalette, 3, uintptr(hdc), uintptr(iLayerPlane), uintptr(bRealize))
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter pAddress has type *C.LPVOID.
// Parameter count has type C.UINT.
// Return value has type C.BOOL.
func ReleaseImageBufferEventsI3D(hDC unsafe.Pointer, pAddress unsafe.Pointer, count unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpReleaseImageBufferEventsI3D, 3, uintptr(hDC), uintptr(pAddress), uintptr(count))
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Parameter hDC has type C.HDC.
// Return value has type C.int.
func ReleasePbufferDCARB(hPbuffer unsafe.Pointer, hDC unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpReleasePbufferDCARB, 2, uintptr(hPbuffer), uintptr(hDC), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFEREXT.
// Parameter hDC has type C.HDC.
// Return value has type C.int.
func ReleasePbufferDCEXT(hPbuffer unsafe.Pointer, hDC unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpReleasePbufferDCEXT, 2, uintptr(hPbuffer), uintptr(hDC), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Parameter iBuffer has type C.int.
// Return value has type C.BOOL.
func ReleaseTexImageARB(hPbuffer unsafe.Pointer, iBuffer unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpReleaseTexImageARB, 2, uintptr(hPbuffer), uintptr(iBuffer), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDc has type C.HDC.
// Parameter hDevice has type C.HVIDEOINPUTDEVICENV.
// Return value has type C.BOOL.
func ReleaseVideoCaptureDeviceNV(hDc unsafe.Pointer, hDevice unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpReleaseVideoCaptureDeviceNV, 2, uintptr(hDc), uintptr(hDevice), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hVideoDevice has type C.HPVIDEODEV.
// Return value has type C.BOOL.
func ReleaseVideoDeviceNV(hVideoDevice unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpReleaseVideoDeviceNV, 1, uintptr(hVideoDevice), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Parameter iVideoBuffer has type C.int.
// Return value has type C.BOOL.
func ReleaseVideoImageNV(hPbuffer unsafe.Pointer, iVideoBuffer unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpReleaseVideoImageNV, 2, uintptr(hPbuffer), uintptr(iVideoBuffer), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Return value has type C.BOOL.
func ResetFrameCountNV(hDC unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpResetFrameCountNV, 1, uintptr(hDC), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hRegion has type C.HANDLE.
// Parameter x has type C.int.
// Parameter y has type C.int.
// Parameter width has type C.int.
// Parameter height has type C.int.
// Parameter xSrc has type C.int.
// Parameter ySrc has type C.int.
// Return value has type C.BOOL.
func RestoreBufferRegionARB(hRegion unsafe.Pointer, x unsafe.Pointer, y unsafe.Pointer, width unsafe.Pointer, height unsafe.Pointer, xSrc unsafe.Pointer, ySrc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall9(gpRestoreBufferRegionARB, 7, uintptr(hRegion), uintptr(x), uintptr(y), uintptr(width), uintptr(height), uintptr(xSrc), uintptr(ySrc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hRegion has type C.HANDLE.
// Parameter x has type C.int.
// Parameter y has type C.int.
// Parameter width has type C.int.
// Parameter height has type C.int.
// Return value has type C.BOOL.
func SaveBufferRegionARB(hRegion unsafe.Pointer, x unsafe.Pointer, y unsafe.Pointer, width unsafe.Pointer, height unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpSaveBufferRegionARB, 5, uintptr(hRegion), uintptr(x), uintptr(y), uintptr(width), uintptr(height), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Parameter iBufferType has type C.int.
// Parameter pulCounterPbuffer has type *C.unsignedlong.
// Parameter bBlock has type C.BOOL.
// Return value has type C.BOOL.
func SendPbufferToVideoNV(hPbuffer unsafe.Pointer, iBufferType unsafe.Pointer, pulCounterPbuffer unsafe.Pointer, bBlock unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpSendPbufferToVideoNV, 4, uintptr(hPbuffer), uintptr(iBufferType), uintptr(pulCounterPbuffer), uintptr(bBlock), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iAttribute has type C.int.
// Parameter piValue has type *C.int.
// Return value has type C.BOOL.
func SetDigitalVideoParametersI3D(hDC unsafe.Pointer, iAttribute unsafe.Pointer, piValue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpSetDigitalVideoParametersI3D, 3, uintptr(hDC), uintptr(iAttribute), uintptr(piValue))
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iEntries has type C.int.
// Parameter puRed has type *C.USHORT.
// Parameter puGreen has type *C.USHORT.
// Parameter puBlue has type *C.USHORT.
// Return value has type C.BOOL.
func SetGammaTableI3D(hDC unsafe.Pointer, iEntries unsafe.Pointer, puRed unsafe.Pointer, puGreen unsafe.Pointer, puBlue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpSetGammaTableI3D, 5, uintptr(hDC), uintptr(iEntries), uintptr(puRed), uintptr(puGreen), uintptr(puBlue), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter iAttribute has type C.int.
// Parameter piValue has type *C.int.
// Return value has type C.BOOL.
func SetGammaTableParametersI3D(hDC unsafe.Pointer, iAttribute unsafe.Pointer, piValue unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpSetGammaTableParametersI3D, 3, uintptr(hDC), uintptr(iAttribute), uintptr(piValue))
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter iLayerPlane has type C.int.
// Parameter iStart has type C.int.
// Parameter cEntries has type C.int.
// Parameter pcr has type *C.COLORREF.
// Return value has type C.int.
func SetLayerPaletteEntries(hdc unsafe.Pointer, iLayerPlane unsafe.Pointer, iStart unsafe.Pointer, cEntries unsafe.Pointer, pcr unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpSetLayerPaletteEntries, 5, uintptr(hdc), uintptr(iLayerPlane), uintptr(iStart), uintptr(cEntries), uintptr(pcr), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hPbuffer has type C.HPBUFFERARB.
// Parameter piAttribList has type *C.int.
// Return value has type C.BOOL.
func SetPbufferAttribARB(hPbuffer unsafe.Pointer, piAttribList unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpSetPbufferAttribARB, 2, uintptr(hPbuffer), uintptr(piAttribList), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter uState has type C.UINT.
// Return value has type C.BOOL.
func SetStereoEmitterState3DL(hDC unsafe.Pointer, uState unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpSetStereoEmitterState3DL, 2, uintptr(hDC), uintptr(uState), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hrcSrvShare has type C.HGLRC.
// Parameter hrcSrvSource has type C.HGLRC.
// Return value has type C.BOOL.
func ShareLists(hrcSrvShare unsafe.Pointer, hrcSrvSource unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpShareLists, 2, uintptr(hrcSrvShare), uintptr(hrcSrvSource), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter target_msc has type C.INT64.
// Parameter divisor has type C.INT64.
// Parameter remainder has type C.INT64.
// Return value has type C.INT64.
func SwapBuffersMscOML(hdc unsafe.Pointer, target_msc unsafe.Pointer, divisor unsafe.Pointer, remainder unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpSwapBuffersMscOML, 4, uintptr(hdc), uintptr(target_msc), uintptr(divisor), uintptr(remainder), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter interval has type C.int.
// Return value has type C.BOOL.
func SwapIntervalEXT(interval unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpSwapIntervalEXT, 1, uintptr(interval), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter fuFlags has type C.UINT.
// Return value has type C.BOOL.
func SwapLayerBuffers(hdc unsafe.Pointer, fuFlags unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall(gpSwapLayerBuffers, 2, uintptr(hdc), uintptr(fuFlags), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter fuPlanes has type C.int.
// Parameter target_msc has type C.INT64.
// Parameter divisor has type C.INT64.
// Parameter remainder has type C.INT64.
// Return value has type C.INT64.
func SwapLayerBuffersMscOML(hdc unsafe.Pointer, fuPlanes unsafe.Pointer, target_msc unsafe.Pointer, divisor unsafe.Pointer, remainder unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpSwapLayerBuffersMscOML, 5, uintptr(hdc), uintptr(fuPlanes), uintptr(target_msc), uintptr(divisor), uintptr(remainder), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter first has type C.DWORD.
// Parameter count has type C.DWORD.
// Parameter listBase has type C.DWORD.
// Return value has type C.BOOL.
func UseFontBitmaps(hDC unsafe.Pointer, first unsafe.Pointer, count unsafe.Pointer, listBase unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpUseFontBitmaps, 4, uintptr(hDC), uintptr(first), uintptr(count), uintptr(listBase), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hDC has type C.HDC.
// Parameter first has type C.DWORD.
// Parameter count has type C.DWORD.
// Parameter listBase has type C.DWORD.
// Parameter deviation has type C.FLOAT.
// Parameter extrusion has type C.FLOAT.
// Parameter format has type C.int.
// Parameter lpgmf has type C.LPGLYPHMETRICSFLOAT.
// Return value has type C.BOOL.
func UseFontOutlines(hDC unsafe.Pointer, first unsafe.Pointer, count unsafe.Pointer, listBase unsafe.Pointer, deviation unsafe.Pointer, extrusion unsafe.Pointer, format unsafe.Pointer, lpgmf unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall9(gpUseFontOutlines, 8, uintptr(hDC), uintptr(first), uintptr(count), uintptr(listBase), uintptr(deviation), uintptr(extrusion), uintptr(format), uintptr(lpgmf), 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter target_msc has type C.INT64.
// Parameter divisor has type C.INT64.
// Parameter remainder has type C.INT64.
// Parameter ust has type *C.INT64.
// Parameter msc has type *C.INT64.
// Parameter sbc has type *C.INT64.
// Return value has type C.BOOL.
func WaitForMscOML(hdc unsafe.Pointer, target_msc unsafe.Pointer, divisor unsafe.Pointer, remainder unsafe.Pointer, ust unsafe.Pointer, msc unsafe.Pointer, sbc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall9(gpWaitForMscOML, 7, uintptr(hdc), uintptr(target_msc), uintptr(divisor), uintptr(remainder), uintptr(ust), uintptr(msc), uintptr(sbc), 0, 0)
	return (unsafe.Pointer)(ret)
}

// Parameter hdc has type C.HDC.
// Parameter target_sbc has type C.INT64.
// Parameter ust has type *C.INT64.
// Parameter msc has type *C.INT64.
// Parameter sbc has type *C.INT64.
// Return value has type C.BOOL.
func WaitForSbcOML(hdc unsafe.Pointer, target_sbc unsafe.Pointer, ust unsafe.Pointer, msc unsafe.Pointer, sbc unsafe.Pointer) unsafe.Pointer {
	ret, _, _ := syscall.Syscall6(gpWaitForSbcOML, 5, uintptr(hdc), uintptr(target_sbc), uintptr(ust), uintptr(msc), uintptr(sbc), 0)
	return (unsafe.Pointer)(ret)
}

// InitWithProcAddrFunc intializes the package using the specified OpenGL
// function pointer loading function. For more cases Init should be used
// instead.
func InitWithProcAddrFunc(getProcAddr func(name string) unsafe.Pointer) error {
	gpChoosePixelFormat = uintptr(getProcAddr("ChoosePixelFormat"))
	if gpChoosePixelFormat == 0 {
		return errors.New("ChoosePixelFormat")
	}
	gpDescribePixelFormat = uintptr(getProcAddr("DescribePixelFormat"))
	if gpDescribePixelFormat == 0 {
		return errors.New("DescribePixelFormat")
	}
	gpGetEnhMetaFilePixelFormat = uintptr(getProcAddr("GetEnhMetaFilePixelFormat"))
	if gpGetEnhMetaFilePixelFormat == 0 {
		return errors.New("GetEnhMetaFilePixelFormat")
	}
	gpGetPixelFormat = uintptr(getProcAddr("GetPixelFormat"))
	if gpGetPixelFormat == 0 {
		return errors.New("GetPixelFormat")
	}
	gpSetPixelFormat = uintptr(getProcAddr("SetPixelFormat"))
	if gpSetPixelFormat == 0 {
		return errors.New("SetPixelFormat")
	}
	gpSwapBuffers = uintptr(getProcAddr("SwapBuffers"))
	if gpSwapBuffers == 0 {
		return errors.New("SwapBuffers")
	}
	gpAllocateMemoryNV = uintptr(getProcAddr("wglAllocateMemoryNV"))
	gpAssociateImageBufferEventsI3D = uintptr(getProcAddr("wglAssociateImageBufferEventsI3D"))
	gpBeginFrameTrackingI3D = uintptr(getProcAddr("wglBeginFrameTrackingI3D"))
	gpBindDisplayColorTableEXT = uintptr(getProcAddr("wglBindDisplayColorTableEXT"))
	gpBindSwapBarrierNV = uintptr(getProcAddr("wglBindSwapBarrierNV"))
	gpBindTexImageARB = uintptr(getProcAddr("wglBindTexImageARB"))
	gpBindVideoCaptureDeviceNV = uintptr(getProcAddr("wglBindVideoCaptureDeviceNV"))
	gpBindVideoDeviceNV = uintptr(getProcAddr("wglBindVideoDeviceNV"))
	gpBindVideoImageNV = uintptr(getProcAddr("wglBindVideoImageNV"))
	gpBlitContextFramebufferAMD = uintptr(getProcAddr("wglBlitContextFramebufferAMD"))
	gpChoosePixelFormatARB = uintptr(getProcAddr("wglChoosePixelFormatARB"))
	gpChoosePixelFormatEXT = uintptr(getProcAddr("wglChoosePixelFormatEXT"))
	gpCopyContext = uintptr(getProcAddr("wglCopyContext"))
	if gpCopyContext == 0 {
		return errors.New("wglCopyContext")
	}
	gpCopyImageSubDataNV = uintptr(getProcAddr("wglCopyImageSubDataNV"))
	gpCreateAffinityDCNV = uintptr(getProcAddr("wglCreateAffinityDCNV"))
	gpCreateAssociatedContextAMD = uintptr(getProcAddr("wglCreateAssociatedContextAMD"))
	gpCreateAssociatedContextAttribsAMD = uintptr(getProcAddr("wglCreateAssociatedContextAttribsAMD"))
	gpCreateBufferRegionARB = uintptr(getProcAddr("wglCreateBufferRegionARB"))
	gpCreateContext = uintptr(getProcAddr("wglCreateContext"))
	if gpCreateContext == 0 {
		return errors.New("wglCreateContext")
	}
	gpCreateContextAttribsARB = uintptr(getProcAddr("wglCreateContextAttribsARB"))
	gpCreateDisplayColorTableEXT = uintptr(getProcAddr("wglCreateDisplayColorTableEXT"))
	gpCreateImageBufferI3D = uintptr(getProcAddr("wglCreateImageBufferI3D"))
	gpCreateLayerContext = uintptr(getProcAddr("wglCreateLayerContext"))
	if gpCreateLayerContext == 0 {
		return errors.New("wglCreateLayerContext")
	}
	gpCreatePbufferARB = uintptr(getProcAddr("wglCreatePbufferARB"))
	gpCreatePbufferEXT = uintptr(getProcAddr("wglCreatePbufferEXT"))
	gpDXCloseDeviceNV = uintptr(getProcAddr("wglDXCloseDeviceNV"))
	gpDXLockObjectsNV = uintptr(getProcAddr("wglDXLockObjectsNV"))
	gpDXObjectAccessNV = uintptr(getProcAddr("wglDXObjectAccessNV"))
	gpDXOpenDeviceNV = uintptr(getProcAddr("wglDXOpenDeviceNV"))
	gpDXRegisterObjectNV = uintptr(getProcAddr("wglDXRegisterObjectNV"))
	gpDXSetResourceShareHandleNV = uintptr(getProcAddr("wglDXSetResourceShareHandleNV"))
	gpDXUnlockObjectsNV = uintptr(getProcAddr("wglDXUnlockObjectsNV"))
	gpDXUnregisterObjectNV = uintptr(getProcAddr("wglDXUnregisterObjectNV"))
	gpDelayBeforeSwapNV = uintptr(getProcAddr("wglDelayBeforeSwapNV"))
	gpDeleteAssociatedContextAMD = uintptr(getProcAddr("wglDeleteAssociatedContextAMD"))
	gpDeleteBufferRegionARB = uintptr(getProcAddr("wglDeleteBufferRegionARB"))
	gpDeleteContext = uintptr(getProcAddr("wglDeleteContext"))
	if gpDeleteContext == 0 {
		return errors.New("wglDeleteContext")
	}
	gpDeleteDCNV = uintptr(getProcAddr("wglDeleteDCNV"))
	gpDescribeLayerPlane = uintptr(getProcAddr("wglDescribeLayerPlane"))
	if gpDescribeLayerPlane == 0 {
		return errors.New("wglDescribeLayerPlane")
	}
	gpDestroyDisplayColorTableEXT = uintptr(getProcAddr("wglDestroyDisplayColorTableEXT"))
	gpDestroyImageBufferI3D = uintptr(getProcAddr("wglDestroyImageBufferI3D"))
	gpDestroyPbufferARB = uintptr(getProcAddr("wglDestroyPbufferARB"))
	gpDestroyPbufferEXT = uintptr(getProcAddr("wglDestroyPbufferEXT"))
	gpDisableFrameLockI3D = uintptr(getProcAddr("wglDisableFrameLockI3D"))
	gpDisableGenlockI3D = uintptr(getProcAddr("wglDisableGenlockI3D"))
	gpEnableFrameLockI3D = uintptr(getProcAddr("wglEnableFrameLockI3D"))
	gpEnableGenlockI3D = uintptr(getProcAddr("wglEnableGenlockI3D"))
	gpEndFrameTrackingI3D = uintptr(getProcAddr("wglEndFrameTrackingI3D"))
	gpEnumGpuDevicesNV = uintptr(getProcAddr("wglEnumGpuDevicesNV"))
	gpEnumGpusFromAffinityDCNV = uintptr(getProcAddr("wglEnumGpusFromAffinityDCNV"))
	gpEnumGpusNV = uintptr(getProcAddr("wglEnumGpusNV"))
	gpEnumerateVideoCaptureDevicesNV = uintptr(getProcAddr("wglEnumerateVideoCaptureDevicesNV"))
	gpEnumerateVideoDevicesNV = uintptr(getProcAddr("wglEnumerateVideoDevicesNV"))
	gpFreeMemoryNV = uintptr(getProcAddr("wglFreeMemoryNV"))
	gpGenlockSampleRateI3D = uintptr(getProcAddr("wglGenlockSampleRateI3D"))
	gpGenlockSourceDelayI3D = uintptr(getProcAddr("wglGenlockSourceDelayI3D"))
	gpGenlockSourceEdgeI3D = uintptr(getProcAddr("wglGenlockSourceEdgeI3D"))
	gpGenlockSourceI3D = uintptr(getProcAddr("wglGenlockSourceI3D"))
	gpGetContextGPUIDAMD = uintptr(getProcAddr("wglGetContextGPUIDAMD"))
	gpGetCurrentAssociatedContextAMD = uintptr(getProcAddr("wglGetCurrentAssociatedContextAMD"))
	gpGetCurrentContext = uintptr(getProcAddr("wglGetCurrentContext"))
	if gpGetCurrentContext == 0 {
		return errors.New("wglGetCurrentContext")
	}
	gpGetCurrentDC = uintptr(getProcAddr("wglGetCurrentDC"))
	if gpGetCurrentDC == 0 {
		return errors.New("wglGetCurrentDC")
	}
	gpGetCurrentReadDCARB = uintptr(getProcAddr("wglGetCurrentReadDCARB"))
	gpGetCurrentReadDCEXT = uintptr(getProcAddr("wglGetCurrentReadDCEXT"))
	gpGetDigitalVideoParametersI3D = uintptr(getProcAddr("wglGetDigitalVideoParametersI3D"))
	gpGetExtensionsStringARB = uintptr(getProcAddr("wglGetExtensionsStringARB"))
	gpGetExtensionsStringEXT = uintptr(getProcAddr("wglGetExtensionsStringEXT"))
	gpGetFrameUsageI3D = uintptr(getProcAddr("wglGetFrameUsageI3D"))
	gpGetGPUIDsAMD = uintptr(getProcAddr("wglGetGPUIDsAMD"))
	gpGetGPUInfoAMD = uintptr(getProcAddr("wglGetGPUInfoAMD"))
	gpGetGammaTableI3D = uintptr(getProcAddr("wglGetGammaTableI3D"))
	gpGetGammaTableParametersI3D = uintptr(getProcAddr("wglGetGammaTableParametersI3D"))
	gpGetGenlockSampleRateI3D = uintptr(getProcAddr("wglGetGenlockSampleRateI3D"))
	gpGetGenlockSourceDelayI3D = uintptr(getProcAddr("wglGetGenlockSourceDelayI3D"))
	gpGetGenlockSourceEdgeI3D = uintptr(getProcAddr("wglGetGenlockSourceEdgeI3D"))
	gpGetGenlockSourceI3D = uintptr(getProcAddr("wglGetGenlockSourceI3D"))
	gpGetLayerPaletteEntries = uintptr(getProcAddr("wglGetLayerPaletteEntries"))
	if gpGetLayerPaletteEntries == 0 {
		return errors.New("wglGetLayerPaletteEntries")
	}
	gpGetMscRateOML = uintptr(getProcAddr("wglGetMscRateOML"))
	gpGetPbufferDCARB = uintptr(getProcAddr("wglGetPbufferDCARB"))
	gpGetPbufferDCEXT = uintptr(getProcAddr("wglGetPbufferDCEXT"))
	gpGetPixelFormatAttribfvARB = uintptr(getProcAddr("wglGetPixelFormatAttribfvARB"))
	gpGetPixelFormatAttribfvEXT = uintptr(getProcAddr("wglGetPixelFormatAttribfvEXT"))
	gpGetPixelFormatAttribivARB = uintptr(getProcAddr("wglGetPixelFormatAttribivARB"))
	gpGetPixelFormatAttribivEXT = uintptr(getProcAddr("wglGetPixelFormatAttribivEXT"))
	gpGetProcAddress = uintptr(getProcAddr("wglGetProcAddress"))
	if gpGetProcAddress == 0 {
		return errors.New("wglGetProcAddress")
	}
	gpGetSwapIntervalEXT = uintptr(getProcAddr("wglGetSwapIntervalEXT"))
	gpGetSyncValuesOML = uintptr(getProcAddr("wglGetSyncValuesOML"))
	gpGetVideoDeviceNV = uintptr(getProcAddr("wglGetVideoDeviceNV"))
	gpGetVideoInfoNV = uintptr(getProcAddr("wglGetVideoInfoNV"))
	gpIsEnabledFrameLockI3D = uintptr(getProcAddr("wglIsEnabledFrameLockI3D"))
	gpIsEnabledGenlockI3D = uintptr(getProcAddr("wglIsEnabledGenlockI3D"))
	gpJoinSwapGroupNV = uintptr(getProcAddr("wglJoinSwapGroupNV"))
	gpLoadDisplayColorTableEXT = uintptr(getProcAddr("wglLoadDisplayColorTableEXT"))
	gpLockVideoCaptureDeviceNV = uintptr(getProcAddr("wglLockVideoCaptureDeviceNV"))
	gpMakeAssociatedContextCurrentAMD = uintptr(getProcAddr("wglMakeAssociatedContextCurrentAMD"))
	gpMakeContextCurrentARB = uintptr(getProcAddr("wglMakeContextCurrentARB"))
	gpMakeContextCurrentEXT = uintptr(getProcAddr("wglMakeContextCurrentEXT"))
	gpMakeCurrent = uintptr(getProcAddr("wglMakeCurrent"))
	if gpMakeCurrent == 0 {
		return errors.New("wglMakeCurrent")
	}
	gpQueryCurrentContextNV = uintptr(getProcAddr("wglQueryCurrentContextNV"))
	gpQueryFrameCountNV = uintptr(getProcAddr("wglQueryFrameCountNV"))
	gpQueryFrameLockMasterI3D = uintptr(getProcAddr("wglQueryFrameLockMasterI3D"))
	gpQueryFrameTrackingI3D = uintptr(getProcAddr("wglQueryFrameTrackingI3D"))
	gpQueryGenlockMaxSourceDelayI3D = uintptr(getProcAddr("wglQueryGenlockMaxSourceDelayI3D"))
	gpQueryMaxSwapGroupsNV = uintptr(getProcAddr("wglQueryMaxSwapGroupsNV"))
	gpQueryPbufferARB = uintptr(getProcAddr("wglQueryPbufferARB"))
	gpQueryPbufferEXT = uintptr(getProcAddr("wglQueryPbufferEXT"))
	gpQuerySwapGroupNV = uintptr(getProcAddr("wglQuerySwapGroupNV"))
	gpQueryVideoCaptureDeviceNV = uintptr(getProcAddr("wglQueryVideoCaptureDeviceNV"))
	gpRealizeLayerPalette = uintptr(getProcAddr("wglRealizeLayerPalette"))
	if gpRealizeLayerPalette == 0 {
		return errors.New("wglRealizeLayerPalette")
	}
	gpReleaseImageBufferEventsI3D = uintptr(getProcAddr("wglReleaseImageBufferEventsI3D"))
	gpReleasePbufferDCARB = uintptr(getProcAddr("wglReleasePbufferDCARB"))
	gpReleasePbufferDCEXT = uintptr(getProcAddr("wglReleasePbufferDCEXT"))
	gpReleaseTexImageARB = uintptr(getProcAddr("wglReleaseTexImageARB"))
	gpReleaseVideoCaptureDeviceNV = uintptr(getProcAddr("wglReleaseVideoCaptureDeviceNV"))
	gpReleaseVideoDeviceNV = uintptr(getProcAddr("wglReleaseVideoDeviceNV"))
	gpReleaseVideoImageNV = uintptr(getProcAddr("wglReleaseVideoImageNV"))
	gpResetFrameCountNV = uintptr(getProcAddr("wglResetFrameCountNV"))
	gpRestoreBufferRegionARB = uintptr(getProcAddr("wglRestoreBufferRegionARB"))
	gpSaveBufferRegionARB = uintptr(getProcAddr("wglSaveBufferRegionARB"))
	gpSendPbufferToVideoNV = uintptr(getProcAddr("wglSendPbufferToVideoNV"))
	gpSetDigitalVideoParametersI3D = uintptr(getProcAddr("wglSetDigitalVideoParametersI3D"))
	gpSetGammaTableI3D = uintptr(getProcAddr("wglSetGammaTableI3D"))
	gpSetGammaTableParametersI3D = uintptr(getProcAddr("wglSetGammaTableParametersI3D"))
	gpSetLayerPaletteEntries = uintptr(getProcAddr("wglSetLayerPaletteEntries"))
	if gpSetLayerPaletteEntries == 0 {
		return errors.New("wglSetLayerPaletteEntries")
	}
	gpSetPbufferAttribARB = uintptr(getProcAddr("wglSetPbufferAttribARB"))
	gpSetStereoEmitterState3DL = uintptr(getProcAddr("wglSetStereoEmitterState3DL"))
	gpShareLists = uintptr(getProcAddr("wglShareLists"))
	if gpShareLists == 0 {
		return errors.New("wglShareLists")
	}
	gpSwapBuffersMscOML = uintptr(getProcAddr("wglSwapBuffersMscOML"))
	gpSwapIntervalEXT = uintptr(getProcAddr("wglSwapIntervalEXT"))
	gpSwapLayerBuffers = uintptr(getProcAddr("wglSwapLayerBuffers"))
	if gpSwapLayerBuffers == 0 {
		return errors.New("wglSwapLayerBuffers")
	}
	gpSwapLayerBuffersMscOML = uintptr(getProcAddr("wglSwapLayerBuffersMscOML"))
	gpUseFontBitmaps = uintptr(getProcAddr("wglUseFontBitmapsW"))
	if gpUseFontBitmaps == 0 {
		return errors.New("wglUseFontBitmaps")
	}
	gpUseFontOutlines = uintptr(getProcAddr("wglUseFontOutlinesW"))
	if gpUseFontOutlines == 0 {
		return errors.New("wglUseFontOutlines")
	}
	gpWaitForMscOML = uintptr(getProcAddr("wglWaitForMscOML"))
	gpWaitForSbcOML = uintptr(getProcAddr("wglWaitForSbcOML"))
	return nil
}
